name: studip-sync
version: git
summary: Synchronize files from Stud.IP
description: |
  Download and synchronize files from Stud.IP -- the campus management
  platform deployed at several German universities. Note that studip-sync
  currently only works at the University of Passau.

grade: devel
confinement: strict

parts:
  studip-sync:
    plugin: python
    python-version: python3
    source: .
    stage-packages: [rsync]

apps:
  studip-sync:
    command: env LC_ALL=C.UTF-8 LANG=C.UTF-8 $SNAP/bin/studip-sync
    plugs: [home, network]
